name: mmdl

modules: 

  balancer: 
    lbModule: 
      ipAddress: "get me with: gcloud compute addresses reserve --region europe-west1 mmdl"
      ipProtocol: tcp
      portRange: 80-44380
      targetModules: 
        - nodejs
    type: LOAD_BALANCING

  firewall: 
    firewallModule: 
      allowed: 
        - IPProtocol: tcp
          ports: 
            - 80
            - 3000
      network: default
      sourceRanges: 
        - 0.0.0.0/0
    type: FIREWALL

  nodejs: 
    replicaPoolModule: 
      numReplicas: 1
      replicaPoolParams: 
        v1beta1: 
          baseInstanceName: nodejs
          disksToCreate: 
            - boot: true
              initializeParams: 
                diskSizeGb: 10
                sourceImage: "https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/backports-debian-7-wheezy-v20140415"
          initAction: setup_vm
          machineType: g1-small
          metadata: 
            items: 
              - key: MMDL_DB_HOST
                value: localhost
              - key: MMDL_DB_PORT
                value: 3306
              - key: MMDL_DB_NAME
                value: minimobiledevicelab
              - key: MMDL_DB_USER
                value: root
              - key: MMDL_DB_PASSWORD
                value: secret
              - key: MMDL_GPLUS_CLIENT_ID
                value: "get me from developers console"
              - key: MMDL_GCM_CLIENT_ID
                value: "google cloud messaging client ID"
              - key: MMDL_WEBHOOK_URL
                value: "http://webhook.example.org/"
              - key: MMDL_WEBHOOK_SECRET
                value: "some-webhook-secret-word"
          networkInterfaces: 
            - accessConfigs: 
                - name: "External NAT"
                  type: ONE_TO_ONE_NAT
              network: default
          zone: europe-west1-b
    type: REPLICA_POOL

actions: 
  setup_vm: 
    commands: 
      - "apt-get update && apt-get install -y nodejs ruby git mysql-client vim bzip2 nginx fcgiwrap"
      - "ln -s /usr/bin/nodejs /usr/bin/node"
      - "cd /tmp && curl http://registry.npmjs.org/npm/-/npm-1.4.7.tgz | tar xzf -"
      - "cd /tmp/package && node cli.js install -g -f"
      - "npm install -g forever grunt-cli bower"
      - "gem install --no-ri --no-rdoc compass"
      - "mkdir -p /apps && useradd -d /apps -s /bin/bash apps && chown -R apps /apps"
      - "%file:mmdl-instance-setup.sh"
