application: primal-gate-91117 
version: 20150410-1
runtime: python27
threadsafe: yes
api_version: 1


handlers:
- url: /scripts
  static_dir: scripts
  secure: always

- url: /styles
  static_dir: styles
  secure: always

- url: /images
  static_dir: images
  secure: always

- url: /bower_components
  static_dir: bower_components
  secure: always

- url: /displays
  static_dir: displays
  secure: always

- url: /elements.html
  static_files: elements.html
  upload: elements.html
  expiration: "0s"
  secure: always

- url: /config.html
  static_files: config.html
  upload: config.html
  expiration: "0s"
  secure: always

- url: /ios/MMDLClient.ipa
  mime_type: application/octet-stream
  static_files: ios/MMDLClient.ipa
  upload: ios/MMDLClient.ipa
  expiration: "0s"

- url: /ios/MMDLClient.plist
  mime_type: application/xml
  static_files: ios/MMDLClient.plist
  upload: ios/MMDLClient.plist
  expiration: "0s"

- url: /ios/
  static_files: ios/index.html
  upload: ios/index.html

- url: /ios/.*
  static_files: ios/index.html
  upload: ios/index.html

- url: /.*
  static_files: index.html
  upload: index.html
  expiration: "0s"
  secure: always



